server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service # Nome da aplicação para o Eureka
  datasource:
    url: jdbc:postgresql://localhost:5433/ead-course
    username: postgres
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqps://oijgbbli:iL-DudOhnSXPLx_3oEtqZcAC4UkZgQjm@leopard.lmq.cloudamqp.com/oijgbbli

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      userEventExchange: ead.userevent
    queue:
      userEventQueue:
        name: ead.userevent.ms.course

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'  # Endereço onde o eureka está disponível.
  instance:
    hostname: localhost
